### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by AlrzAmini** [VahidFarahmandian/Jinget#54]
**Describe the bug**
some misspelling in datetime utilities

**To Reproduce**
1. Go to ['dateTimeUtilities'](https://github.com/VahidFarahmandian/Jinget/blob/main/01-Core/Jinget.Core/Utilities/DateTimeUtility.cs)
2. georgianDate -> gregorian

`public static string ToSolarDate(DateTime georgianDate)
        {
            var calendar = new PersianCalendar();
            return
                $"{calendar.GetYear(georgianDate)}/{calendar.GetMonth(georgianDate):D2}/{calendar.GetDayOfMonth(georgianDate):D2}";
        }
`

` public static DateTime ToGeorgianDate(string persianDate) => DateTime.Parse(persianDate, new CultureInfo("fa-IR"));`

**Comment by VahidFarahmandian** [comment]
Thanks. the misspelling error have been resolved and will be available in the next release(2.0.5), just before the July 20th.
